


services:


  jenkins:
    build: ./jenkins
    image: jenkins

    ports:
      - "8080:8080"
      - "50000:50000"

    privileged: true

    user: root



    volumes:
      - ./jenkins/.jen:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
  


  graphdb:
    #build: ./graphdb
    image: ontotext/graphdb:9.11.2-se
    ports:
      - "7200:7200"

  db:
  #  build: ./mysql
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: diaspora_v2
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
    ports:
      - "42333:3306"



